FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y\
        net-tools \
        iptables \
 && rm -rf /var/lib/apt/lists/*

COPY bin/cniserver /var/libnetwork/bin/
COPY cniserver.sh /var/libnetwork/
COPY bin/cnictl /var/libnetwork/bin/
COPY net.conf  /var/libnetwork/config/

ENTRYPOINT ["/var/libnetwork/cniserver.sh"]
